services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./${HomerConf}:/www/assets # Make sure your local config directory exists
    ports:
      - 8888:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
