services:
  
  prometheus:
    container_name: Prometheus_Windows
    image: prom/prometheus:latest
    volumes:
      - prometheus_Data_Windows:/prometheus
      - ./${Prometheusconf}:/etc/prometheus
    ports:
      - "9091:9090"
    restart: always

volumes:
  prometheus_Data_Windows:
