services:
  Portainer:
    container_name: Portainer
    image: portainer/portainer-ce:2.21.4
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - container_data:/data
    restart: always
volumes:
  container_data:
