services:
  grafana:
    container_name: Grafana
    image: grafana/grafana:latest
    volumes:
      - grafana-config:/etc/grafana
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
volumes:
  grafana-config:
  grafana-storage:
