services:
  Agente-portainer:
    container_name: Agente-portainer
    image: portainer/agent:2.21.4
    ports:
      - "9001:9001"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host
    restart: always
